name:                nowdoc
version:             0.1.0.4
github:              "YoshikuniJujo/nowdoc"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "2018 Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md
- samples/*

# Metadata used when publishing your package
synopsis:            Here document without variable expansion like PHP Nowdoc
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/nowdoc#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

library:
  source-dirs: src

tests:
  nowdoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nowdoc
